models:
  violence: "../models/violence.pt"
  license_plate: "../models/license_plate.pt"
  rubbish: "../models/garbage.pt"
  bicylce: "../models/yolo11n.pt"
  pets: "../models/yolo11n.pt"
  vehicle: "../models/yolo11n.pt"
  person: "../models/yolo11n.pt"

confidence:
  violence: 0.8
  license_plate: 0.6
  license_plate_11x: 0.6
  fire-and-smoke: 0.7
  rubbish: 0.8

classes:
  bicycle: [1]
  pets: [15,16]
  vehicle: [2,3,5,7]
  person: [0]

robot:
  rtsp://localhost:8554/stream: "local test"

camera:
  rtsp://localhost:8554/stream: "camera test"

# API endpoint settings
api:
  post_endpoint: "http://localhost:8080/api/detections"
  timeout: 10


