version: '3.8'

services:
  yolo-detection-person:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=person
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  yolo-detection-rubbish:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=rubbish
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
  
  yolo-detection-vehicle:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=vehicle
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  # yolo-detection-violence:
  #   build: .
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - YOLO_TYPE=violence
  #     - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
  #     - YOLO_BLUR=true
  #   volumes:
  #     - ./models:/app/models:ro
  #     - ./scripts:/app/scripts:ro
  #     - ./config.yaml:/app/config.yaml:ro
  #     - /home/data/pics/AI/:/app/output
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   working_dir: /app
  #   command: ["python", "/app/scripts/yolo_detection_self.py"]
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4G
  #       reservations:
  #         memory: 2G
  #   restart: unless-stopped

  yolo-detection-bicylce:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=bicylce
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
  
  yolo-detection-pets:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=pets
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211003
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  yolo-detection-person-2:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=person
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211004
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
  
  yolo-detection-rubbish-2:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=rubbish
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211004
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  yolo-detection-bicylce-2:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=bicylce
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211004
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
  
  yolo-detection-pets-2:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=pets
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211004
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  yolo-detection-vehicle-2:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_TYPE=vehicle
      - YOLO_STREAM=rtsp://192.144.182.93:10554/34020000001110000211_34020000001310211004
      - YOLO_BLUR=true
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  post-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scripts:/app/scripts:ro
      - ./output:/app/output
    working_dir: /app
    command: ["python", "/app/scripts/post_server.py"]
    restart: unless-stopped

volumes:
  output: