version: '3.8'

services:
  yolo-detection:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    command: ["python", "/app/scripts/yolo_detection_self.py"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  post-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scripts:/app/scripts:ro
      - ./output:/app/output
    working_dir: /app
    command: ["python", "/app/scripts/post_server.py"]
    restart: unless-stopped

volumes:
  output: