version: '3.8'

services:
  image-description:
    build: .
    container_name: image-description-service
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models:ro
      - ./scripts:/app/scripts:ro
      - ./config.yaml:/app/config.yaml:ro
      - /home/data/pics/AI/:/app/output
      - ./images:/app/images
      - ./logs:/app/logs
    working_dir: /app
    command: ["python", "/app/scripts/image_description.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "image-description"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
    network_mode: "host"

volumes:
  output:
