version: '3.8'

services:
  detection-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WORKERS=4
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./results:/app/results
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - detection-service
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  models:
  uploads:
  results: